### ISSUE TITLE
Log: Auto Clear

### ISSUE THREAD

**Issue by Fhizbang** [CriticalHit-d13/d13#15]
the log in /logs/log.txt

should be automatically cleared every 24-48 hours or something

but i dont want to use a CRON for this

rather with a timestamp and whenever a page is refreshed

**Comment by BlackScorp** [comment]
i would like to implement Monolog Logger, it has already a "FileRotationHandler" you can configure how many logfiles should be maximum saved and so on

**Comment by Fhizbang** [comment]
Yeah, we could need a more sophisticated solution anyway. Right now its just a ugly text file with stuff dumped into. It should be easy to adjust the logger class.
