### ISSUE TITLE
Feedback messages

### ISSUE THREAD

**Issue by Fhizbang** [CriticalHit-d13/d13#22]
there is an age-old system that is mostly used by all "Control" classes. this system saves a feedback message to echo it later. it uses a simple string $message, but the string is currently not forwarded to the template engine anymore.

there should be a new class (d13_notes) where you can add messages one at a time. pull the latest message, or all messages, remove messages and so on.

then, the template class should fetch the latest message when assembling a page and echo that message somewhere, using a nice message box like design.

the class is easy to write, template engine easy to adjust.

the big question is when/where to forward $message to d13_notes ($message is a local string variable within each function of a class).

**Comment by Pietrafixa** [comment]
Hello @Fhizbang I found very interesting this project. Finally, a modern browser-game open source! All those found on the network are outdated and do not adapt to mobile devices. I hope that you will continue to work and update this game engine.
An advice I can give you is to create a line of development to understand which changes or what features will be added in the course of development. A site that I can recommend is https://trello.com/ (but there are many other network). Then another thing, I tried to play from smartphones (5.5 inches) is the images overlap one other. This makes it impossible to interact with the game.
**However I plan to compliment you for this project.** Good job.
