### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by stuartmoseley** [CriticalHit-d13/d13#26]
Hi I tried to install this on my domain but I'm getting errors, can you mail me at stuartmoseley27@gmail.com , my domain is http://z2h.site/d13/
I get the same error when I try to run http://z2h.site/d13/install/install.php
My have tried using both pho 5.6 and 7.0

I was wondering if you needed a helping hand with design or things

**Comment by Fhizbang** [comment]
you got mail!
